name: Esbuild rebuild

on:
  push:
    paths: 
      - 'src/**'
  pull_request:
    paths: 
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}        
        
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
      
    - name: Setup node 
      uses: actions/setup-node@v3
      with:
        node-version: current
        cache: 'npm'
        
    - name: Clean dependencies installation
      run: npm ci
      
    - name: Esbuild rebuild
      run: npm run build
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "rebuild: implemented commit ${{ github.sha }}"
        file_pattern: '*/out.js'
        add_options: '--force'
